### ISSUE TITLE
Unexpected type mismatches in correct programs

### ISSUE THREAD

**Issue by developedby** [Kindelia/Kind2#38]
I've stumbled upon two occasions where a program does not typecheck despite being typed correctly.

First, the shorter one:
```
A (t: Type) : Type
A.new <t: Type> (x: t) : (A t)

Fn <t: Type> (x: (A (A t))) : (A (A t))
Fn t1 (A.new t (A.new t2 x)) = (A.new (A.new x))
```
Gives the error:
```
Type mismatch.
- Expected: (A (A t1))
- Detected: (A (A t2))
Context:
- t1 : Type
- t  : Type
- t  = (A t1)
- t  = (A t2)
- t2 : Type
- x  : t2
On 'test.kind2':
   5 | Fn t1 (A.new t (A.new t2 x)) = *(A.new (A.new x))*
```
It doesn't understand that `t1` and `t2` must be the same.  
Changing the last line to `Fn t1 (A.new (A t) (A.new t2 x)) = (A.new (A.new x))`, matching with `(A t)` instead of `t`, the type checker then works as expected.

The second example is:
```
Nat : Type
Nat = (n: Type) (n -> n) -> n -> n

Zero : Nat
Zero = @n @s @z z

Suc (a: Nat): Nat
Suc a = @n @s @z (s (a n s z))

Vec (a: Type) (n: Nat) : Type
Vec a n =
  (v: Nat -> Type)
  (s: (n_: Nat) a -> (v n_) -> (v (Suc n_)))
  (z: (v Zero))
  (v n)
```
Which gives the error:
```
Type mismatch.
- Expected: (n: Type) ((n -> n) -> (n -> n))
- Detected: Nat
Context:
- a  : Type
- n  : (n: Type) ((n -> n) -> (n -> n))
- v  : (Nat -> Type)
- n_ : Nat
- _  : a
- _  : (v n_)
On 'bench/asymptotics_vec.kind2':
  14 |   (s: (n_: Nat) a -> (v n_) -> (v (Suc *n_*)))
```
It fails to understand that `Nat` is defined as `(n: Type) ((n -> n) -> (n -> n))`.  
Changing the last rule of the code to the following, it checks as expected:
```
Nat : Type
Nat = (n: Type) (n -> n) -> n -> n

Zero : Nat
Zero = @n @s @z z

Suc (a: Nat): Nat
Suc a = @n @s @z (s (a n s z))

Vec (a: Type) (n: Nat) : Type
Vec a n =
  let nat = Nat
  (v: nat -> Type)
  (s: (n_: nat) a -> (v n_) -> (v (Suc n_)))
  (z: (v Zero))
  (v n)
```
Adding the `let` expression fixes the program somehow.

The first error seems to have always happened.  
The second one started at commit `748a97`, where it crashed instead of checking, and after `44a289` it gave the type error above.

**Comment by VictorTaelin** [comment]
The first problem is not a bug, just an incomplete proof. To accept that kind of program, and due to some type-checker optimizations, which are part of the reason it is so fast, Kind's type-checker needs some additional proof-work that wouldn't be needed in Agda. Let me explain. In your first program, suppose you write:

```
A (t: Type) : Type
A.new <t: Type> (x: t) : (A t)

Fn <t: Type> (x: (A (A t))) : (A (A t))
Fn t (A.new t1 (A.new t2 x)) =
  let a = (A.new x)
  ?
```

Here, you have the following context:

```
Type mismatch.
- Expected: (A (A t))
- Detected: ?
Context:
- t  : Type
- t1 : Type
- t1 = (A t)
- t1 = (A t2)
- t2 : Type
- x  : t2
- a  : (A t2)
- a  = (A.new t2 x)
On 'bad.kind2':
   7 |   ?
```

Notice that our goal is `(A (A t))`, and we have, in context, `a : (A t2)`. What you did is: you constructed `(A.new a)`, which has type `(A (A t2))`, and returned it. But that is **not** the type of our goal, which is `(A (A t))`. Here, `t` and `t2` are different variables. In some languages like Agda, the type-checker will keep track of all variables that can be identified, and accept this answer via unification. Kind2 does not do that automatically. Instead, it just tracks all the possible values that a variable can have on the context, and allows the programmer to explicitly perform the required up-casts to construct the desired type. Notice the following lines of the context above:

```
- t1 = (A t)
- t1 = (A t2)
```

That means that, as far as equality is concerned, the compiler is able to identify `t1` with `(A t)`, and `t1` with `(A t2)`. But it is **not** able to identify `(A t)` with `(A t2)`, because the following line isn't present:

```
- (A t) = (A t2)
```

In other words, this is an instance where Agda's unification will "complete the proof" for you, but Kind demands some additional reasoning. It is not hard, though. To complete this proof, you just need to notice the following:

```
if a : (A t2), then a : t1, due to the first equality above
if a : (A t1), then a : (A t), due to the second equality above
```

In other words, we are allowed to do this:

```
Fn <t: Type> (x: (A (A t))) : (A (A t))
Fn t (A.new t1 (A.new t2 x)) =
  let a = ((A.new x) :: t1) :: (A t)
  ?
```

Which results in the following context:

```
Type mismatch.
- Expected: (A (A t))
- Detected: ?
Context:
- t  : Type
- t1 : Type
- t1 = (A t)
- t1 = (A t2)
- t2 : Type
- x  : t2
- a  : (A t)
- a  = (A.new t2 x)
On 'bad.kind2':
   7 |   ?
```

Notice that the type of `a` changed from `(A t2)` to `(A t)`. That allows us to construct `(A.new a) : (A (A t))`, completing the proof:

```
Fn <t: Type> (x: (A (A t))) : (A (A t))
Fn t (A.new t1 (A.new t2 x)) =
  let a = ((A.new x) :: t1) :: (A t)
  (A.new a)
```
In this case, though, casting twice was overkill. We can remove the second annotation:

```
Fn <t: Type> (x: (A (A t))) : (A (A t))
Fn t (A.new t1 (A.new t2 x)) =
  let a = (A.new x) :: t1
  (A.new a)
```

When we do that, the returned value will have type `(A t1)` instead of `(A (A t))`, which is the goal. But in this case, it is fine, because we have `t1 = (A t)` in context, so Kind can perform the reduction.

## In short...

Whenever you see:

```
- t = u
- t = v
```

In context, it means Kind is capable of reducing `t` to both `u` and `v`, for equality purposes. But it is **not** able to reduce `u` to `v`, or `v` to `u`. Because of that, if you have some `val : u`, and you want to cast it to `val : v`, you must first cast it to `val : t` (which works because `t = u`), and then cast it to `val : v` (which works, because `t = v`). Hope this part is cleared up! I'll cover the next problem in a moment.
